package com.nimet.rcrs.model;

import com.nimet.rcrs.repository.DataStore;

import java.util.List;

public class Admin extends User {

    private final String staffId;

    // Injected after construction by AuthenticationService (or Main)
    private Catalogue catalogue;
    private DataStore dataStore;

    public Admin(String userId, String fullName, String passwordHash, String staffId) {
        super(userId, fullName, passwordHash);
        this.staffId = staffId;
    }

    // Retrieves a fully loaded Student object from storage
    public Student getRegistrationData(String studentId) {
        if (dataStore == null) throw new IllegalStateException("DataStore not wired into Admin.");
        return dataStore.loadStudent(studentId);
    }

    // Removes a course from both the catalogue and persistent storage
    public void removeCourse(String code) {
        if (catalogue == null || dataStore == null)
            throw new IllegalStateException("Catalogue/DataStore not wired into Admin.");
        Course course = catalogue.findByCode(code);
        if (course != null) {
            catalogue.removeCourse(course);
            dataStore.deleteCourse(code);
        }
    }

    public List<Course> viewCatalogue() {
        if (catalogue == null) throw new IllegalStateException("Catalogue not wired into Admin.");
        return catalogue.getAllCourses();
    }

    // Seeds the catalogue with all NiMet courses from DataStore and returns them
    public List<Course> seedCatalogue() {
        if (catalogue == null || dataStore == null)
            throw new IllegalStateException("Catalogue/DataStore not wired into Admin.");
        List<Course> courses = dataStore.getAllCourses();
        for (Course c : courses) {
            catalogue.addCourse(c);
        }
        return courses;
    }

    // Produces a plain-text summary report listing all students and their registrations
    public String generateStudentReport() {
        if (dataStore == null) throw new IllegalStateException("DataStore not wired into Admin.");
        List<Student> students = dataStore.getAllStudents();
        StringBuilder sb = new StringBuilder();
        sb.append("=== NiMet Student Registration Report ===\n\n");
        for (Student s : students) {
            sb.append(s).append("\n");
            List<Registration> regs = dataStore.findRegistration(s);
            if (regs.isEmpty()) {
                sb.append("  No registrations on file.\n");
            } else {
                for (Registration r : regs) {
                    sb.append("  ").append(r.getSemester())
                      .append(" — ").append(r.getSelectedCourses().size()).append(" course(s)\n");
                }
            }
            sb.append("\n");
        }
        return sb.toString();
    }

    // Updates the editable profile fields of an existing student.
    // studentId and fullName are intentionally excluded — those are immutable.
    public void updateStudentProfile(Student student, String address, String email,
                                     String phone, Programme programme,
                                     int currentYear, int currentSemester) {
        student.setAddress(address);
        student.setEmail(email);
        student.setPhone(phone);
        student.setProgramme(programme);
        student.setCurrentYear(currentYear);
        student.setCurrentSemester(currentSemester);
    }

    // Registers a new student, stores them in DataStore, and returns the created Student.
    // tempPassword is the plain-text value generated by the caller (Main); Admin stores the hash.
    public Student registerStudent(String fullName, String address, String email,
                                   String phone, Programme programme, String tempPassword) {
        if (dataStore == null) throw new IllegalStateException("DataStore not wired into Admin.");
        int admissionYear = java.time.Year.now().getValue();
        String studentId  = dataStore.generateNextStudentId(admissionYear);
        String hashedPwd  = DataStore.sha256(tempPassword);

        Student student = new Student(
                studentId, fullName, hashedPwd,
                studentId, programme,
                admissionYear, 1, 1,
                address, email, phone
        );
        student.setTemporaryPassword(true);
        dataStore.saveStudent(student);
        return student;
    }

    public String getStaffId() { return staffId; }

    public void setCatalogue(Catalogue catalogue)   { this.catalogue = catalogue; }
    public void setDataStore(DataStore dataStore)   { this.dataStore = dataStore; }

    @Override
    public String toString() {
        return String.format("%s | %s [ADMIN]", staffId, fullName);
    }
}
